### ISSUE TITLE
Hard to read hyperlinks in dark mode

### ISSUE THREAD

**Issue by yurivangeffen** [prefix-dev/prefix-dev#1]
Love Prefix! As a token of support I want to leave the first Issue ❤️ .
No biggie, but hyperlinks are sometimes a bit hard to read (dark on dark):

<img width="736" alt="Screenshot 2022-11-16 at 11 21 16" src="https://user-images.githubusercontent.com/4107720/202155215-e0a42ded-ba96-432e-91cb-0bf431e7178f.png">

**Comment by baszalmstra** [comment]
Hey @yurivangeffen! Good spot! I appreciate it! I'll fix it ASAP.

**Comment by wolfv** [comment]
Thanks for filing the issue!
