### ISSUE TITLE
Bad contrast on prefix.dev for win-arm64

### ISSUE THREAD

**Issue by AntoinePrv** [prefix-dev/prefix-dev#18]
https://prefix.dev/channels/conda-forge/packages/vs2022_win-64

![Screenshot from 2023-06-07 17-07-18](https://github.com/prefix-dev/prefix-dev/assets/11088808/7522b816-45d5-4c86-a52b-bd89420e8baa)

**Comment by ruben-arts** [comment]
Thanks for letting us know. Should be fixed in the next release!

**Comment by ruben-arts** [comment]
This is fixed :smile:
