### ISSUE TITLE
Pixi documentation not showing in navigation bar

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/prefix-dev#19]
The pixi documentation is not showing up in the navigation bar if you are on https://prefix.dev/docs/prefix/overview for example. It only shows up when you actually are on a pixi site.

![image](https://github.com/prefix-dev/prefix-dev/assets/29506042/4557760b-0348-4507-9a60-5688ac8172d5)
![image](https://github.com/prefix-dev/prefix-dev/assets/29506042/4276bde7-e45c-45fe-9ac3-9dcd7e9a05bb)

**Comment by ruben-arts** [comment]
Good catch! We've got some work in the pipeline to improve the website.  When this is pushed to public this should also be fixed.

**Comment by ruben-arts** [comment]
Release is done, this works for me now :smile:
