### ISSUE TITLE
Pixi documentation subdirectories not working

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/prefix-dev#20]
https://github.com/prefix-dev/prefix-dev/assets/29506042/74800562-c100-454e-b294-87978618b4e4

Also, the hyperlinks contain a `/` too much

![image](https://github.com/prefix-dev/prefix-dev/assets/29506042/f8c09a6a-d679-480d-ad28-3818bda56238)

**Comment by ruben-arts** [comment]
Thanks again! Here the same issue holds as with the #19 we updated the docs without releasing the website which has some new logic to generate those urls. Sorry for the inconvenience.

**Comment by ruben-arts** [comment]
Release is done, this works for me now! :smile:
