### ISSUE TITLE
Search not finding a package?!

### ISSUE THREAD

**Issue by dhirschfeld** [prefix-dev/prefix-dev#24]
https://github.com/conda-forge/dlltracer-feedstock

![image](https://github.com/prefix-dev/prefix-dev/assets/881019/c92e2f96-a97d-4b43-9933-8178b2581a1e)

**Comment by dhirschfeld** [comment]
It seems there may be an issue with the info coming from `anaconda.org`:

![image](https://github.com/prefix-dev/prefix-dev/assets/881019/175dd3ab-acb3-4bed-b025-fd89779b6c55)

**Comment by dhirschfeld** [comment]
Eh? Now, I'm confused 😕 

```
❯ mamba search dlltracer
Getting repodata from channels...

conda-forge/noarch                                  12.3MB @  10.2MB/s  1.2s
conda-forge/win-64                                  19.3MB @  15.9MB/s  1.2s


No entries matching "dlltracer" found
Channels may not be configured. Try giving a channel with '-c,--channel' option, or use `--use-local=1` to search for installed packages.
```

**Comment by dhirschfeld** [comment]
Ok, seems it's only publishing to a dev label:

![image](https://github.com/prefix-dev/prefix-dev/assets/881019/d37d86ab-5fd7-4263-a3c0-a37a5fd01ab8)

**Comment by wolfv** [comment]
thanks for figuring this out! Indeed, prefix.dev doesn't have support for labels yet. I think I am not a big fan of labels (vs. just creating more channels), but maybe I can be convinced :)

**Comment by dhirschfeld** [comment]
Yeah, I think channels are the way to go. I'm not sure what the benefits of labels over channels are... or really what the differences are from an end-user point-of-view.

With `micromamba` able to install a package with `dev-channel::dev-package` without opening up `dev-channel` to be used for other packages you only need a single dev channel for all packages.
