### ISSUE TITLE
Feature Request: Visualize labels of packages/files

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/prefix-dev#3]
Hee peeps,

Following the [issue](https://github.com/RoboStack/ros-noetic/issues/310) we had today. We think it would help if we also could see which packages are broken. Which is done in conda-forge with labels. This feature doesn't seem available on your website/database.

Some ideas on UX:
- Visualize all labels on a variant, if any, make it red if broken in labels
- Visualize all labels on a package (the overview page), if any
- Make it available through the graphql schema on package/pacakge variant
- If the 'broken' label is used on a variant and a package depends on exactly that version mark it red in the dependencies of the other package's variant. 
- Track a list/overview of packages just marked as broken. 

I just want to say having your website available when debugging `micromamba` solving errors is awesome, 100x quicker vs anaconda.org 
We also used your `graphql` api to find packages, which we're using in a working env but we though might not be available, going from a mamba list output to a qraphql query. 

Keep up the good work!!

**Comment by baszalmstra** [comment]
Thanks @ruben-arts , that seems like a good idea! Im not really a fan of the anaconda labels. I think they are rather complex for what they offer. I think the different use cases could be solved in better ways. 

For example in this specific case it would be nice if on https://prefix.dev you can see:

* "missing"/"deleted": These packages and their content has been removed
* "yanked": These packages are no longer available in the repodata (so they wont be selected during solving) but can still be downloaded (so are still valid in lock files).

We could indicate that with a label per variant perhaps? WDYT @wolfv @tdejager ?

**Comment by wolfv** [comment]
I think if we show a "yanked" label for each package that is in the "removed" list (at the end of the repodata.json file) that would be great!

**Comment by ruben-arts** [comment]
That would be awesome and a solution to my issue!

**Comment by ruben-arts** [comment]
So funny story, I started working at prefix.dev and now made this feature. You can now clearly see if a package variant is yanked from the list of package variants. Additionally, you can see the repo data patches in the list of dependencies if that would ever be a problem.
