### ISSUE TITLE
Some published packages' builds on conda-forge are unvisible on prefix.dev

### ISSUE THREAD

**Issue by jjerphan** [prefix-dev/prefix-dev#42]
Some packages' builds published on conda-forge aren't visible on their page on prefix.dev.

This is for instance the case of some Windows builds of [folly](https://github.com/conda-forge/folly-feedstock/).

Whilst they are indeed all visible on [anaconda's website](https://anaconda.org/conda-forge/folly/files) but some of them are missing on [prefix.dev's](https://prefix.dev/channels/conda-forge/packages/folly).

One instance of the problem exists for [`folly-2024.05.02.00-h23e0033_0.conda`](https://anaconda.org/conda-forge/folly/2024.05.02.00/download/win-64/folly-2024.05.02.00-h23e0033_0.conda).

---

First observed in https://github.com/conda-forge/folly-feedstock/issues/176#issuecomment-2122118227.

**Comment by wolfv** [comment]
Hmm, interesting. On https://prefix.dev/api/graphql I can find the packages for win-64 as well - using the following query:

```graphql
{
  package(channelName: "conda-forge", name: "folly") {
    variants(limit: 300) {
      page {
        filename
        platform
        md5
        yankedReason
        repoDataPatches
      }
    }
  }
}
```

Maybe we need to revalidate the server side rendered react :/

**Comment by jjerphan** [comment]
Thank you for looking at it. :)

**Comment by baszalmstra** [comment]
Looking at the package page now it seems that they are all there, so closing this for now. Please let us know if you find other discrepancies!
