### ISSUE TITLE
Broken Mamba docs link on Prefix documentation homepage

### ISSUE THREAD

**Issue by jatonline** [prefix-dev/prefix-dev#46]
On this page: https://prefix.dev/docs/prefix/overview there are links to the Mamba docs.

The tile "Mamba - Introduction to the mamba package manager" has a broken link to: https://prefix.dev/docs//mamba/introduction which should instead be: https://prefix.dev/docs/mamba/overview

**Comment by baszalmstra** [comment]
Thanks for reporting! This has been fixed.
