### ISSUE TITLE
Download links on website point to anaconda.org

### ISSUE THREAD

**Issue by jamesmyatt** [prefix-dev/prefix-dev#50]
The download links on the website refer to anaconda.org rather than prefix.dev. Is this deliberate?

For example, on https://prefix.dev/channels/conda-forge/packages/python, the first download link is https://conda.anaconda.org/conda-forge/osx-arm64/python-3.13.0rc2-h206b6c5_100_cp313.conda

![image](https://github.com/user-attachments/assets/59439b38-1ca0-4668-9b12-9431191cf2ac)

**Comment by wolfv** [comment]
Hey @jamesmyatt - yes, for some time this was deliberate - but we are ready to change that now.

**Comment by jamesmyatt** [comment]
Seems to be fixed now. Thanks
