### ISSUE TITLE
Cannot log in using github

### ISSUE THREAD

**Issue by maartenbreddels** [prefix-dev/prefix-dev#6]
Congrats on the new article 🎉 
But I got this when using the github login:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/1765949/220434531-e3902827-a3d3-4020-a9d9-84fa4c28f6a1.png">

Browser: brave (tried also with shields down, no change)

**Comment by pditommaso** [comment]
Same here, empty error message and the browser shows this URL 

```
https://prefix.dev/error?id=c6f63857-9863-49fb-914d-fb45be295411
```

**Comment by wolfv** [comment]
thanks! looking into this!

**Comment by tdejager** [comment]
Could you try it again, we think that it should work now :)

**Comment by maartenbreddels** [comment]
Works for me :)

**Comment by pditommaso** [comment]
solved!

**Comment by baszalmstra** [comment]
Awesome!
