### ISSUE TITLE
menu does not work on safari mobile

### ISSUE THREAD

**Issue by maartenbreddels** [prefix-dev/prefix-dev#7]
If I click the hamburger icon, it stays black and I see no dialog. It looks something like this (screenshot taken on desktop, just to show what it looks like)
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1765949/220458342-72a2510e-d60f-43a5-a19b-6d88c5de3f7e.png">

**Comment by baszalmstra** [comment]
Hey @maartenbreddels! 

That shouldn't happen! Which iDevice are you using?

**Comment by maartenbreddels** [comment]
Hmmm, after a page refresh it works, maybe a glitch/timing issue that doesn’t happen when the cache is filled.

**Comment by maartenbreddels** [comment]
It is on iOS 16.2 btw
