### ISSUE TITLE
support '_' in environment names

### ISSUE THREAD

**Issue by mfansler** [prefix-dev/prefix-dev#9]
I attempted to create an environment with the name `bioc_3_16`, but was unable. It only worked after removing the underscores (`bioc316`). This is my preferred convention for indicating versions in the environment name and works locally with Conda and Mamba. Please consider adding support for underscores.

**Comment by wolfv** [comment]
Hi @mfansler thanks for the feedback! We'll get this done soon

**Comment by ruben-arts** [comment]
He @mfansler, we updated the environments and you can now use underscores in the name :smiley:
